### ISSUE TITLE
logtool_single 有更新计划吗?

### ISSUE THREAD

**Issue by Jiacheng-z** [ccinos/act_dps_show#1]
您好. 一直有在使用这个功能. 目前国服已更新新的零式, 有计划支持新的区域可选项吗? 
感谢

**Comment by ccinos** [comment]
已经更新可选区域
![QQ图片20210608095732](https://user-images.githubusercontent.com/37493483/121110489-f42cbe80-c83f-11eb-87ef-6b9c05ad88ca.png)
